#ifndef BASESUPLUGIN_GLOBAL_H
#define BASESUPLUGIN_GLOBAL_H

#include <QGlobal.h>

#ifdef BASESUPLUGIN_LIB
# define BASESUPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define BASESUPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // BASESUPLUGIN_GLOBAL_H
