#ifndef SPEECH_UTILITY_GLOBAL_H
#define SPEECH_UTILITY_GLOBAL_H

#include <QGlobal.h>

#ifdef SPEECH_UTILITY__LIB
# define SPEECH_UTILITY_EXPORT Q_DECL_EXPORT
#else
# define SPEECH_UTILITY_EXPORT Q_DECL_IMPORT
#endif

#endif // SPEECH_UTILITY_GLOBAL_H
