#ifndef VADMARKINGPLUGIN_GLOBAL_H
#define VADMARKINGPLUGIN_GLOBAL_H

#include <QGlobal.h>

#ifdef VADMARKINGPLUGIN_LIB
# define VADMARKINGPLUGIN_EXPORT Q_DECL_EXPORT
#else
# define VADMARKINGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // VADMARKINGPLUGIN_GLOBAL_H
