#ifndef VADMARKINGPLUGIN_GLOBAL_H
#define VADMARKINGPLUGIN_GLOBAL_H

#include <QGlobal.h>

#ifdef SPEAKERSCOUNTLUGIN_LIB
# define SPEAKERSCOUNTLUGIN_EXPORT Q_DECL_EXPORT
#else
# define SPEAKERSCOUNTLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // VADMARKINGPLUGIN_GLOBAL_H
